# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDesign.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1565, 705)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 1080))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setItalic(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/LOGO1.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(320, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(_fromUtf8("QGroupBox{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QToolButton{\n"
"background-color:transparent;\n"
"border:none;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border-width: 2px;\n"
"background-color:qlineargradient(spread:pad, x1:0.965, y1:0.04, x2:0.975773, y2:1, stop:0 rgba(214, 225, 239, 255));\n"
"\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"background-color:rgb(193,210,238);\n"
"border-width: 1px;\n"
"border-color:rgb(5, 54, 118);\n"
"border-style: solid;\n"
"}\n"
"\n"
"QTabWidget{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"background-color:rgb(193,210,238);\n"
"border-width: 1px;\n"
"border-color:rgb(5, 54, 118);\n"
"border-style: solid;\n"
"\n"
"}\n"
"\n"
"#QWidget#baselayer{\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QWidget#vl_qwt_ProcessImgView{\n"
"border-width: 0.5px;\n"
"border-color:rgb(255, 85, 0);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"QWidget#controlBox{\n"
"border-width: 0.5px;\n"
"border-color:rgb(85, 170, 0);\n"
"border-style: solid;\n"
"border-radius:3px;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"QGroupBox{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::pane { \n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:transparent;\n"
"\n"
"}\n"
"\n"
"QTabBar {\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"background-color:transparent;\n"
"color:rgb(255, 0, 0);\n"
"}\n"
"QTabBar::tab:unselected{\n"
"background-color:transparent;\n"
"}"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Objects = QtGui.QWidget()
        self.Objects.setObjectName(_fromUtf8("Objects"))
        self.gridLayout_16 = QtGui.QGridLayout(self.Objects)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gp_object_tools = QtGui.QGroupBox(self.Objects)
        self.gp_object_tools.setMinimumSize(QtCore.QSize(280, 150))
        self.gp_object_tools.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gp_object_tools.setFont(font)
        self.gp_object_tools.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gp_object_tools.setObjectName(_fromUtf8("gp_object_tools"))
        self.btn_start = QtGui.QToolButton(self.gp_object_tools)
        self.btn_start.setGeometry(QtCore.QRect(30, 50, 61, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btn_start.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Play-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_start.setIcon(icon1)
        self.btn_start.setIconSize(QtCore.QSize(18, 18))
        self.btn_start.setCheckable(True)
        self.btn_start.setAutoExclusive(False)
        self.btn_start.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.btn_login = QtGui.QToolButton(self.gp_object_tools)
        self.btn_login.setGeometry(QtCore.QRect(160, 50, 61, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btn_login.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("resources/icons/hand_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_login.setIcon(icon2)
        self.btn_login.setIconSize(QtCore.QSize(22, 22))
        self.btn_login.setCheckable(True)
        self.btn_login.setAutoExclusive(False)
        self.btn_login.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_login.setObjectName(_fromUtf8("btn_login"))
        self.gridLayout_16.addWidget(self.gp_object_tools, 0, 0, 1, 1)
        self.gp_object_specification = QtGui.QGroupBox(self.Objects)
        self.gp_object_specification.setMinimumSize(QtCore.QSize(280, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gp_object_specification.setFont(font)
        self.gp_object_specification.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gp_object_specification.setObjectName(_fromUtf8("gp_object_specification"))
        self.sa_reportCard = QtGui.QScrollArea(self.gp_object_specification)
        self.sa_reportCard.setGeometry(QtCore.QRect(10, 150, 261, 291))
        self.sa_reportCard.setMinimumSize(QtCore.QSize(0, 163))
        self.sa_reportCard.setMaximumSize(QtCore.QSize(16777215, 500))
        self.sa_reportCard.setWidgetResizable(True)
        self.sa_reportCard.setObjectName(_fromUtf8("sa_reportCard"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 259, 289))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.lbl_mstrwdt = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_mstrwdt.setGeometry(QtCore.QRect(10, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_mstrwdt.setFont(font)
        self.lbl_mstrwdt.setObjectName(_fromUtf8("lbl_mstrwdt"))
        self.lbl_tol = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_tol.setGeometry(QtCore.QRect(10, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_tol.setFont(font)
        self.lbl_tol.setObjectName(_fromUtf8("lbl_tol"))
        self.lbl_mm1 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_mm1.setGeometry(QtCore.QRect(220, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_mm1.setFont(font)
        self.lbl_mm1.setObjectName(_fromUtf8("lbl_mm1"))
        self.p_tolerance = QtGui.QTextEdit(self.scrollAreaWidgetContents_5)
        self.p_tolerance.setGeometry(QtCore.QRect(120, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_tolerance.setFont(font)
        self.p_tolerance.setObjectName(_fromUtf8("p_tolerance"))
        self.lbl_mm = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_mm.setGeometry(QtCore.QRect(220, 150, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_mm.setFont(font)
        self.lbl_mm.setObjectName(_fromUtf8("lbl_mm"))
        self.val_mstrwdt = QtGui.QTextEdit(self.scrollAreaWidgetContents_5)
        self.val_mstrwdt.setGeometry(QtCore.QRect(120, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.val_mstrwdt.setFont(font)
        self.val_mstrwdt.setObjectName(_fromUtf8("val_mstrwdt"))
        self.lbl_mstrwdt_3 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_mstrwdt_3.setGeometry(QtCore.QRect(10, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_mstrwdt_3.setFont(font)
        self.lbl_mstrwdt_3.setObjectName(_fromUtf8("lbl_mstrwdt_3"))
        self.val_awdth = QtGui.QTextEdit(self.scrollAreaWidgetContents_5)
        self.val_awdth.setGeometry(QtCore.QRect(120, 90, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.val_awdth.setFont(font)
        self.val_awdth.setObjectName(_fromUtf8("val_awdth"))
        self.lbl_mm_2 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_mm_2.setGeometry(QtCore.QRect(220, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_mm_2.setFont(font)
        self.lbl_mm_2.setObjectName(_fromUtf8("lbl_mm_2"))
        self.n_tolerance = QtGui.QTextEdit(self.scrollAreaWidgetContents_5)
        self.n_tolerance.setGeometry(QtCore.QRect(120, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.n_tolerance.setFont(font)
        self.n_tolerance.setObjectName(_fromUtf8("n_tolerance"))
        self.lbl_mm_3 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_mm_3.setGeometry(QtCore.QRect(220, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_mm_3.setFont(font)
        self.lbl_mm_3.setObjectName(_fromUtf8("lbl_mm_3"))
        self.lbl_tol_2 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_tol_2.setGeometry(QtCore.QRect(10, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_tol_2.setFont(font)
        self.lbl_tol_2.setObjectName(_fromUtf8("lbl_tol_2"))
        self.sa_reportCard.setWidget(self.scrollAreaWidgetContents_5)
        self.val_file_name = QtGui.QTextEdit(self.gp_object_specification)
        self.val_file_name.setGeometry(QtCore.QRect(10, 88, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.val_file_name.setFont(font)
        self.val_file_name.setObjectName(_fromUtf8("val_file_name"))
        self.btn_fname = QtGui.QPushButton(self.gp_object_specification)
        self.btn_fname.setGeometry(QtCore.QRect(180, 90, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_fname.setFont(font)
        self.btn_fname.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_fname.setObjectName(_fromUtf8("btn_fname"))
        self.btn_manual = QtGui.QToolButton(self.gp_object_specification)
        self.btn_manual.setGeometry(QtCore.QRect(30, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btn_manual.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Industry-Manual-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_manual.setIcon(icon3)
        self.btn_manual.setIconSize(QtCore.QSize(18, 18))
        self.btn_manual.setCheckable(True)
        self.btn_manual.setAutoExclusive(False)
        self.btn_manual.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_manual.setObjectName(_fromUtf8("btn_manual"))
        self.btn_measure = QtGui.QToolButton(self.gp_object_specification)
        self.btn_measure.setGeometry(QtCore.QRect(160, 10, 71, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btn_measure.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("resources/icons/corner-resize-maximum-increase-vector-design-tool-36591f7d0275c6f4-512x512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_measure.setIcon(icon4)
        self.btn_measure.setIconSize(QtCore.QSize(18, 18))
        self.btn_measure.setCheckable(True)
        self.btn_measure.setAutoExclusive(False)
        self.btn_measure.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_measure.setObjectName(_fromUtf8("btn_measure"))
        self.gridLayout_16.addWidget(self.gp_object_specification, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Objects, _fromUtf8(""))
        self.Settings = QtGui.QWidget()
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.gridLayout_14 = QtGui.QGridLayout(self.Settings)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.groupBox = QtGui.QGroupBox(self.Settings)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gpCameraTools = QtGui.QGroupBox(self.groupBox)
        self.gpCameraTools.setGeometry(QtCore.QRect(40, 20, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpCameraTools.setFont(font)
        self.gpCameraTools.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpCameraTools.setObjectName(_fromUtf8("gpCameraTools"))
        self.btnCam_0 = QtGui.QToolButton(self.gpCameraTools)
        self.btnCam_0.setGeometry(QtCore.QRect(10, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnCam_0.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/camera.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCam_0.setIcon(icon5)
        self.btnCam_0.setCheckable(True)
        self.btnCam_0.setChecked(True)
        self.btnCam_0.setAutoExclusive(True)
        self.btnCam_0.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnCam_0.setObjectName(_fromUtf8("btnCam_0"))
        self.btnBackup = QtGui.QToolButton(self.groupBox)
        self.btnBackup.setGeometry(QtCore.QRect(30, 150, 51, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnBackup.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Backup-Sync-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBackup.setIcon(icon6)
        self.btnBackup.setIconSize(QtCore.QSize(18, 18))
        self.btnBackup.setCheckable(False)
        self.btnBackup.setAutoExclusive(False)
        self.btnBackup.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnBackup.setObjectName(_fromUtf8("btnBackup"))
        self.btnReload = QtGui.QToolButton(self.groupBox)
        self.btnReload.setGeometry(QtCore.QRect(100, 150, 51, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnReload.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Reload icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReload.setIcon(icon7)
        self.btnReload.setIconSize(QtCore.QSize(18, 18))
        self.btnReload.setCheckable(False)
        self.btnReload.setAutoExclusive(False)
        self.btnReload.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnReload.setObjectName(_fromUtf8("btnReload"))
        self.btnTest = QtGui.QToolButton(self.groupBox)
        self.btnTest.setGeometry(QtCore.QRect(170, 150, 41, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnTest.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/test icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTest.setIcon(icon8)
        self.btnTest.setIconSize(QtCore.QSize(18, 18))
        self.btnTest.setCheckable(True)
        self.btnTest.setAutoExclusive(False)
        self.btnTest.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnTest.setObjectName(_fromUtf8("btnTest"))
        self.swParameter = QtGui.QStackedWidget(self.groupBox)
        self.swParameter.setGeometry(QtCore.QRect(0, 250, 258, 371))
        self.swParameter.setObjectName(_fromUtf8("swParameter"))
        self.parm_cam_0 = QtGui.QWidget()
        self.parm_cam_0.setObjectName(_fromUtf8("parm_cam_0"))
        self.gridLayout_11 = QtGui.QGridLayout(self.parm_cam_0)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.saCam_0 = QtGui.QScrollArea(self.parm_cam_0)
        self.saCam_0.setWidgetResizable(True)
        self.saCam_0.setObjectName(_fromUtf8("saCam_0"))
        self.sawcsCam_0 = QtGui.QWidget()
        self.sawcsCam_0.setGeometry(QtCore.QRect(0, 0, 238, 118))
        self.sawcsCam_0.setObjectName(_fromUtf8("sawcsCam_0"))
        self.gridLayout_8 = QtGui.QGridLayout(self.sawcsCam_0)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.fmCamSample_0 = QtGui.QFrame(self.sawcsCam_0)
        self.fmCamSample_0.setMinimumSize(QtCore.QSize(220, 100))
        self.fmCamSample_0.setMaximumSize(QtCore.QSize(220, 100))
        self.fmCamSample_0.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmCamSample_0.setFrameShadow(QtGui.QFrame.Raised)
        self.fmCamSample_0.setObjectName(_fromUtf8("fmCamSample_0"))
        self.hsCamSample_0 = QtGui.QSlider(self.fmCamSample_0)
        self.hsCamSample_0.setGeometry(QtCore.QRect(20, 20, 181, 29))
        self.hsCamSample_0.setOrientation(QtCore.Qt.Horizontal)
        self.hsCamSample_0.setObjectName(_fromUtf8("hsCamSample_0"))
        self.lbCamSample_0 = QtGui.QLabel(self.fmCamSample_0)
        self.lbCamSample_0.setGeometry(QtCore.QRect(30, 60, 171, 31))
        self.lbCamSample_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCamSample_0.setObjectName(_fromUtf8("lbCamSample_0"))
        self.gridLayout_8.addWidget(self.fmCamSample_0, 0, 0, 1, 1)
        self.saCam_0.setWidget(self.sawcsCam_0)
        self.gridLayout_11.addWidget(self.saCam_0, 1, 0, 1, 1)
        self.gpSourceTools_0 = QtGui.QGroupBox(self.parm_cam_0)
        self.gpSourceTools_0.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpSourceTools_0.setFont(font)
        self.gpSourceTools_0.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpSourceTools_0.setObjectName(_fromUtf8("gpSourceTools_0"))
        self.btnRecord_3 = QtGui.QToolButton(self.gpSourceTools_0)
        self.btnRecord_3.setGeometry(QtCore.QRect(160, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnRecord_3.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Actions-media-record-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRecord_3.setIcon(icon9)
        self.btnRecord_3.setIconSize(QtCore.QSize(12, 12))
        self.btnRecord_3.setCheckable(True)
        self.btnRecord_3.setAutoExclusive(True)
        self.btnRecord_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnRecord_3.setObjectName(_fromUtf8("btnRecord_3"))
        self.btnLive_3 = QtGui.QToolButton(self.gpSourceTools_0)
        self.btnLive_3.setGeometry(QtCore.QRect(100, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnLive_3.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Pause-Normal-Red-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLive_3.setIcon(icon10)
        self.btnLive_3.setIconSize(QtCore.QSize(12, 12))
        self.btnLive_3.setCheckable(True)
        self.btnLive_3.setChecked(False)
        self.btnLive_3.setAutoExclusive(True)
        self.btnLive_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnLive_3.setObjectName(_fromUtf8("btnLive_3"))
        self.btnVideo_3 = QtGui.QToolButton(self.gpSourceTools_0)
        self.btnVideo_3.setGeometry(QtCore.QRect(30, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnVideo_3.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/play-movies-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVideo_3.setIcon(icon11)
        self.btnVideo_3.setIconSize(QtCore.QSize(12, 12))
        self.btnVideo_3.setCheckable(True)
        self.btnVideo_3.setAutoExclusive(True)
        self.btnVideo_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnVideo_3.setObjectName(_fromUtf8("btnVideo_3"))
        self.gridLayout_11.addWidget(self.gpSourceTools_0, 0, 0, 1, 1)
        self.swParameter.addWidget(self.parm_cam_0)
        self.parm_cam_1 = QtGui.QWidget()
        self.parm_cam_1.setObjectName(_fromUtf8("parm_cam_1"))
        self.gridLayout_12 = QtGui.QGridLayout(self.parm_cam_1)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gpSourceTools_1 = QtGui.QGroupBox(self.parm_cam_1)
        self.gpSourceTools_1.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpSourceTools_1.setFont(font)
        self.gpSourceTools_1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpSourceTools_1.setObjectName(_fromUtf8("gpSourceTools_1"))
        self.btnRecord_4 = QtGui.QToolButton(self.gpSourceTools_1)
        self.btnRecord_4.setGeometry(QtCore.QRect(160, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnRecord_4.setFont(font)
        self.btnRecord_4.setIcon(icon9)
        self.btnRecord_4.setIconSize(QtCore.QSize(12, 12))
        self.btnRecord_4.setCheckable(True)
        self.btnRecord_4.setAutoExclusive(True)
        self.btnRecord_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnRecord_4.setObjectName(_fromUtf8("btnRecord_4"))
        self.btnLive_4 = QtGui.QToolButton(self.gpSourceTools_1)
        self.btnLive_4.setGeometry(QtCore.QRect(100, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnLive_4.setFont(font)
        self.btnLive_4.setIcon(icon10)
        self.btnLive_4.setIconSize(QtCore.QSize(12, 12))
        self.btnLive_4.setCheckable(True)
        self.btnLive_4.setChecked(False)
        self.btnLive_4.setAutoExclusive(True)
        self.btnLive_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnLive_4.setObjectName(_fromUtf8("btnLive_4"))
        self.btnVideo_4 = QtGui.QToolButton(self.gpSourceTools_1)
        self.btnVideo_4.setGeometry(QtCore.QRect(30, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnVideo_4.setFont(font)
        self.btnVideo_4.setIcon(icon11)
        self.btnVideo_4.setIconSize(QtCore.QSize(12, 12))
        self.btnVideo_4.setCheckable(True)
        self.btnVideo_4.setAutoExclusive(True)
        self.btnVideo_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnVideo_4.setObjectName(_fromUtf8("btnVideo_4"))
        self.gridLayout_12.addWidget(self.gpSourceTools_1, 0, 0, 1, 1)
        self.saCam_1 = QtGui.QScrollArea(self.parm_cam_1)
        self.saCam_1.setWidgetResizable(True)
        self.saCam_1.setObjectName(_fromUtf8("saCam_1"))
        self.sawcsCam_1 = QtGui.QWidget()
        self.sawcsCam_1.setGeometry(QtCore.QRect(0, 0, 238, 245))
        self.sawcsCam_1.setObjectName(_fromUtf8("sawcsCam_1"))
        self.gl_setting_cam_1 = QtGui.QGridLayout(self.sawcsCam_1)
        self.gl_setting_cam_1.setMargin(0)
        self.gl_setting_cam_1.setObjectName(_fromUtf8("gl_setting_cam_1"))
        self.fmCamSample_1 = QtGui.QFrame(self.sawcsCam_1)
        self.fmCamSample_1.setMinimumSize(QtCore.QSize(220, 100))
        self.fmCamSample_1.setMaximumSize(QtCore.QSize(220, 100))
        self.fmCamSample_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmCamSample_1.setFrameShadow(QtGui.QFrame.Raised)
        self.fmCamSample_1.setObjectName(_fromUtf8("fmCamSample_1"))
        self.hsCamSample_1 = QtGui.QSlider(self.fmCamSample_1)
        self.hsCamSample_1.setGeometry(QtCore.QRect(20, 20, 181, 29))
        self.hsCamSample_1.setOrientation(QtCore.Qt.Horizontal)
        self.hsCamSample_1.setObjectName(_fromUtf8("hsCamSample_1"))
        self.lbCamSample_1 = QtGui.QLabel(self.fmCamSample_1)
        self.lbCamSample_1.setGeometry(QtCore.QRect(30, 60, 171, 31))
        self.lbCamSample_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCamSample_1.setObjectName(_fromUtf8("lbCamSample_1"))
        self.gl_setting_cam_1.addWidget(self.fmCamSample_1, 1, 0, 1, 1)
        self.saCam_1.setWidget(self.sawcsCam_1)
        self.gridLayout_12.addWidget(self.saCam_1, 1, 0, 1, 1)
        self.swParameter.addWidget(self.parm_cam_1)
        self.parm_cam_2 = QtGui.QWidget()
        self.parm_cam_2.setObjectName(_fromUtf8("parm_cam_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.parm_cam_2)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.saCam_2 = QtGui.QScrollArea(self.parm_cam_2)
        self.saCam_2.setWidgetResizable(True)
        self.saCam_2.setObjectName(_fromUtf8("saCam_2"))
        self.sawcsCam_2 = QtGui.QWidget()
        self.sawcsCam_2.setGeometry(QtCore.QRect(0, 0, 238, 224))
        self.sawcsCam_2.setObjectName(_fromUtf8("sawcsCam_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.sawcsCam_2)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.fmCamSample_2 = QtGui.QFrame(self.sawcsCam_2)
        self.fmCamSample_2.setMinimumSize(QtCore.QSize(220, 100))
        self.fmCamSample_2.setMaximumSize(QtCore.QSize(220, 100))
        self.fmCamSample_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmCamSample_2.setFrameShadow(QtGui.QFrame.Raised)
        self.fmCamSample_2.setObjectName(_fromUtf8("fmCamSample_2"))
        self.hsCamSample_2 = QtGui.QSlider(self.fmCamSample_2)
        self.hsCamSample_2.setGeometry(QtCore.QRect(20, 20, 181, 29))
        self.hsCamSample_2.setOrientation(QtCore.Qt.Horizontal)
        self.hsCamSample_2.setObjectName(_fromUtf8("hsCamSample_2"))
        self.lbCamSample_2 = QtGui.QLabel(self.fmCamSample_2)
        self.lbCamSample_2.setGeometry(QtCore.QRect(30, 60, 171, 31))
        self.lbCamSample_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCamSample_2.setObjectName(_fromUtf8("lbCamSample_2"))
        self.gridLayout_10.addWidget(self.fmCamSample_2, 1, 0, 1, 1)
        self.gpSourceTools_2 = QtGui.QGroupBox(self.sawcsCam_2)
        self.gpSourceTools_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpSourceTools_2.setFont(font)
        self.gpSourceTools_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpSourceTools_2.setObjectName(_fromUtf8("gpSourceTools_2"))
        self.btnVideo_2 = QtGui.QToolButton(self.gpSourceTools_2)
        self.btnVideo_2.setGeometry(QtCore.QRect(20, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnVideo_2.setFont(font)
        self.btnVideo_2.setIcon(icon11)
        self.btnVideo_2.setIconSize(QtCore.QSize(12, 12))
        self.btnVideo_2.setCheckable(True)
        self.btnVideo_2.setAutoExclusive(True)
        self.btnVideo_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnVideo_2.setObjectName(_fromUtf8("btnVideo_2"))
        self.btnRecord_2 = QtGui.QToolButton(self.gpSourceTools_2)
        self.btnRecord_2.setGeometry(QtCore.QRect(150, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnRecord_2.setFont(font)
        self.btnRecord_2.setIcon(icon9)
        self.btnRecord_2.setIconSize(QtCore.QSize(12, 12))
        self.btnRecord_2.setCheckable(True)
        self.btnRecord_2.setAutoExclusive(True)
        self.btnRecord_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnRecord_2.setObjectName(_fromUtf8("btnRecord_2"))
        self.btnLive_2 = QtGui.QToolButton(self.gpSourceTools_2)
        self.btnLive_2.setGeometry(QtCore.QRect(90, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnLive_2.setFont(font)
        self.btnLive_2.setIcon(icon10)
        self.btnLive_2.setIconSize(QtCore.QSize(12, 12))
        self.btnLive_2.setCheckable(True)
        self.btnLive_2.setChecked(False)
        self.btnLive_2.setAutoExclusive(True)
        self.btnLive_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnLive_2.setObjectName(_fromUtf8("btnLive_2"))
        self.gridLayout_10.addWidget(self.gpSourceTools_2, 0, 0, 1, 1)
        self.saCam_2.setWidget(self.sawcsCam_2)
        self.gridLayout_13.addWidget(self.saCam_2, 1, 0, 1, 1)
        self.swParameter.addWidget(self.parm_cam_2)
        self.val_actol = QtGui.QTextEdit(self.groupBox)
        self.val_actol.setGeometry(QtCore.QRect(140, 110, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.val_actol.setFont(font)
        self.val_actol.setObjectName(_fromUtf8("val_actol"))
        self.lbl_actol = QtGui.QLabel(self.groupBox)
        self.lbl_actol.setGeometry(QtCore.QRect(30, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_actol.setFont(font)
        self.lbl_actol.setObjectName(_fromUtf8("lbl_actol"))
        self.gridLayout_14.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Settings, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.swView = QtGui.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.swView.setFont(font)
        self.swView.setStyleSheet(_fromUtf8("QStackedWidget{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}"))
        self.swView.setObjectName(_fromUtf8("swView"))
        self.live_view = QtGui.QWidget()
        self.live_view.setObjectName(_fromUtf8("live_view"))
        self.gridLayout = QtGui.QGridLayout(self.live_view)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbCam_0 = QtGui.QGroupBox(self.live_view)
        self.gbCam_0.setObjectName(_fromUtf8("gbCam_0"))
        self.lbCam_0 = QtGui.QLabel(self.gbCam_0)
        self.lbCam_0.setGeometry(QtCore.QRect(60, 120, 521, 461))
        self.lbCam_0.setMinimumSize(QtCore.QSize(180, 180))
        self.lbCam_0.setMaximumSize(QtCore.QSize(720, 640))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.lbCam_0.setFont(font)
        self.lbCam_0.setStyleSheet(_fromUtf8("QLabel{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}"))
        self.lbCam_0.setText(_fromUtf8(""))
        self.lbCam_0.setPixmap(QtGui.QPixmap(_fromUtf8("ICONS/LOGO1.jpg")))
        self.lbCam_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCam_0.setObjectName(_fromUtf8("lbCam_0"))
        self.lbl_mode = QtGui.QLabel(self.gbCam_0)
        self.lbl_mode.setGeometry(QtCore.QRect(60, 50, 271, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_mode.setFont(font)
        self.lbl_mode.setObjectName(_fromUtf8("lbl_mode"))
        self.lbl_warning = QtGui.QLabel(self.gbCam_0)
        self.lbl_warning.setGeometry(QtCore.QRect(640, 110, 291, 471))
        self.lbl_warning.setMinimumSize(QtCore.QSize(180, 180))
        self.lbl_warning.setMaximumSize(QtCore.QSize(720, 640))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.lbl_warning.setFont(font)
        self.lbl_warning.setStyleSheet(_fromUtf8("QLabel{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}"))
        self.lbl_warning.setFrameShape(QtGui.QFrame.Box)
        self.lbl_warning.setText(_fromUtf8(""))
        self.lbl_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_warning.setObjectName(_fromUtf8("lbl_warning"))
        self.lbl_warn = QtGui.QLabel(self.gbCam_0)
        self.lbl_warn.setGeometry(QtCore.QRect(670, 50, 271, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_warn.setFont(font)
        self.lbl_warn.setObjectName(_fromUtf8("lbl_warn"))
        self.gridLayout.addWidget(self.gbCam_0, 0, 0, 1, 1)
        self.swView.addWidget(self.live_view)
        self.test_view = QtGui.QWidget()
        self.test_view.setObjectName(_fromUtf8("test_view"))
        self.lb_test_1 = QtGui.QLabel(self.test_view)
        self.lb_test_1.setGeometry(QtCore.QRect(670, 220, 451, 361))
        self.lb_test_1.setMinimumSize(QtCore.QSize(300, 200))
        self.lb_test_1.setMaximumSize(QtCore.QSize(640, 480))
        self.lb_test_1.setFrameShape(QtGui.QFrame.Box)
        self.lb_test_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_test_1.setObjectName(_fromUtf8("lb_test_1"))
        self.lb_test_2 = QtGui.QLabel(self.test_view)
        self.lb_test_2.setGeometry(QtCore.QRect(122, 217, 451, 361))
        self.lb_test_2.setMinimumSize(QtCore.QSize(300, 200))
        self.lb_test_2.setMaximumSize(QtCore.QSize(640, 480))
        self.lb_test_2.setFrameShape(QtGui.QFrame.Box)
        self.lb_test_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_test_2.setObjectName(_fromUtf8("lb_test_2"))
        self.swView.addWidget(self.test_view)
        self.gridLayout_2.addWidget(self.swView, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.swParameter.setCurrentIndex(1)
        self.swView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual Inspection Machine", None))
        self.gp_object_tools.setTitle(_translate("MainWindow", "Object tools", None))
        self.btn_start.setText(_translate("MainWindow", "Start", None))
        self.btn_login.setText(_translate("MainWindow", "login", None))
        self.gp_object_specification.setTitle(_translate("MainWindow", "Result", None))
        self.lbl_mstrwdt.setText(_translate("MainWindow", "Part Width", None))
        self.lbl_tol.setText(_translate("MainWindow", "Tolerance +", None))
        self.lbl_mm1.setText(_translate("MainWindow", "mm", None))
        self.p_tolerance.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">0.5</span></p></body></html>", None))
        self.lbl_mm.setText(_translate("MainWindow", "mm", None))
        self.val_mstrwdt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">000</span></p></body></html>", None))
        self.lbl_mstrwdt_3.setText(_translate("MainWindow", "Actual Width", None))
        self.val_awdth.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">246</span></p></body></html>", None))
        self.lbl_mm_2.setText(_translate("MainWindow", "mm", None))
        self.n_tolerance.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">0.5</span></p></body></html>", None))
        self.lbl_mm_3.setText(_translate("MainWindow", "mm", None))
        self.lbl_tol_2.setText(_translate("MainWindow", "Tolerance -", None))
        self.val_file_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">FILE_NAME</span></p></body></html>", None))
        self.btn_fname.setText(_translate("MainWindow", "Set", None))
        self.btn_manual.setText(_translate("MainWindow", "Manual", None))
        self.btn_measure.setText(_translate("MainWindow", "Measure", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Objects), _translate("MainWindow", "Objects", None))
        self.groupBox.setTitle(_translate("MainWindow", "Tools", None))
        self.gpCameraTools.setTitle(_translate("MainWindow", "Camera tools", None))
        self.btnCam_0.setText(_translate("MainWindow", "CAM0", None))
        self.btnBackup.setText(_translate("MainWindow", "Backup", None))
        self.btnReload.setText(_translate("MainWindow", "Reload", None))
        self.btnTest.setText(_translate("MainWindow", "Test", None))
        self.lbCamSample_0.setText(_translate("MainWindow", "#", None))
        self.gpSourceTools_0.setTitle(_translate("MainWindow", "Source tools", None))
        self.btnRecord_3.setText(_translate("MainWindow", "Record", None))
        self.btnLive_3.setText(_translate("MainWindow", "Live", None))
        self.btnVideo_3.setText(_translate("MainWindow", "Video", None))
        self.gpSourceTools_1.setTitle(_translate("MainWindow", "Source tools", None))
        self.btnRecord_4.setText(_translate("MainWindow", "Record", None))
        self.btnLive_4.setText(_translate("MainWindow", "Live", None))
        self.btnVideo_4.setText(_translate("MainWindow", "Video", None))
        self.lbCamSample_1.setText(_translate("MainWindow", "#", None))
        self.lbCamSample_2.setText(_translate("MainWindow", "#", None))
        self.gpSourceTools_2.setTitle(_translate("MainWindow", "Source tools", None))
        self.btnVideo_2.setText(_translate("MainWindow", "Video", None))
        self.btnRecord_2.setText(_translate("MainWindow", "Record", None))
        self.btnLive_2.setText(_translate("MainWindow", "Live", None))
        self.val_actol.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">0.5</span></p></body></html>", None))
        self.lbl_actol.setText(_translate("MainWindow", "Actual Tol", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings", None))
        self.gbCam_0.setTitle(_translate("MainWindow", "Camera-#", None))
        self.lbl_mode.setText(_translate("MainWindow", "LIVE", None))
        self.lbl_warn.setText(_translate("MainWindow", "WARNING WINDOW", None))
        self.lb_test_1.setText(_translate("MainWindow", "img_1", None))
        self.lb_test_2.setText(_translate("MainWindow", "img_2", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

